### ISSUE TITLE
Greet With Deadline Server check should be context.DeadlineExceeded

### ISSUE THREAD

**Issue by maneeshchaturvedi** [simplesteph/grpc-go-course#13]
In the example for deadline, the server should check for DeadlineExceeded instead of cancelled, otherwise the if block will not be entered. 
Instead of 
`if ctx.Err() == context.Cancelled {
//do stuff here
}`

it should be
`if ctx.Err() == context.DeadlineExceeded {
//do stuff here
}`

**Comment by simplesteph** [comment]
good poitn, I'll accept a PR On this :)

**Comment by maneeshchaturvedi** [comment]
okies.I'll raise it.

**Comment by maneeshchaturvedi** [comment]
Created a PR.
