### ISSUE TITLE
"transport: authentication handshake failed: x509: certificate relies on legacy Common Name field, use SANs instead"

### ISSUE THREAD

**Issue by AJackTi** [simplesteph/grpc-go-course#25]
Hello everyone
After I created the certificate, I run the client program I met some bugs. It looks like the under image 
<img width="1433" alt="image" src="https://user-images.githubusercontent.com/20319611/175757418-72726e44-68c3-4b15-9a0f-3f1b4218375a.png">

And this is a `instructions.sh`
<img width="928" alt="image" src="https://user-images.githubusercontent.com/20319611/175757462-d7134592-6166-4482-a6bf-6755e5d4a5e4.png">

Could you help me? Thank all.

**Comment by rendyuwu** [comment]
I have the same issue and for me, it is solved with change the serverNameOverride from "" to "localhost"

![image](https://user-images.githubusercontent.com/65700377/205684842-af54255c-ac31-43ba-ba01-6e737a44a0b7.png)
